const express = require('express');
require('dotenv').config();

const app = express();
const port = process.env.PORT || 3000; // Use a variável de ambiente PORT

app.use(express.json());

const tabela_brasileirao = [
    {
      posicao: 1,
      pontos: 57,
      time: {
        time_id: 22,
        nome_popular: "Botafogo",
        sigla: "BOT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349052558.svg",
      },
      jogos: 28,
      vitorias: 17,
      empates: 6,
      derrotas: 5,
      gols_pro: 46,
      gols_contra: 25,
      saldo_gols: 21,
      aproveitamento: 67,
      variacao_posicao: 0,
      ultimos_jogos: ["e", "v", "v", "v", "e"],
    },
    {
      posicao: 2,
      pontos: 56,
      time: {
        time_id: 56,
        nome_popular: "Palmeiras",
        sigla: "PAL",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a1cf247.svg",
      },
      jogos: 28,
      vitorias: 17,
      empates: 5,
      derrotas: 6,
      gols_pro: 46,
      gols_contra: 20,
      saldo_gols: 26,
      aproveitamento: 66,
      variacao_posicao: 0,
      ultimos_jogos: ["v", "v", "v", "v", "v"],
    },
    {
      posicao: 3,
      pontos: 55,
      time: {
        time_id: 131,
        nome_popular: "Fortaleza",
        sigla: "FOR",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34c76d067.svg",
      },
      jogos: 28,
      vitorias: 16,
      empates: 7,
      derrotas: 5,
      gols_pro: 37,
      gols_contra: 26,
      saldo_gols: 11,
      aproveitamento: 65,
      variacao_posicao: 0,
      ultimos_jogos: ["v", "d", "e", "v", "v"],
    },
    {
      posicao: 4,
      pontos: 48,
      time: {
        time_id: 18,
        nome_popular: "Flamengo",
        sigla: "FLA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d348e3f815.svg",
      },
      jogos: 27,
      vitorias: 14,
      empates: 6,
      derrotas: 7,
      gols_pro: 43,
      gols_contra: 32,
      saldo_gols: 11,
      aproveitamento: 59,
      variacao_posicao: 0,
      ultimos_jogos: ["v", "d", "e", "d", "v"],
    },
    {
      posicao: 5,
      pontos: 47,
      time: {
        time_id: 57,
        nome_popular: "São Paulo",
        sigla: "SAO",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a23c311.svg",
      },
      jogos: 28,
      vitorias: 14,
      empates: 5,
      derrotas: 9,
      gols_pro: 38,
      gols_contra: 30,
      saldo_gols: 8,
      aproveitamento: 55,
      variacao_posicao: 0,
      ultimos_jogos: ["v", "d", "v", "d", "v"],
    },
    {
      posicao: 6,
      pontos: 45,
      time: {
        time_id: 68,
        nome_popular: "Bahia",
        sigla: "BAH",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a8b6bd8.svg",
      },
      jogos: 28,
      vitorias: 13,
      empates: 6,
      derrotas: 9,
      gols_pro: 39,
      gols_contra: 31,
      saldo_gols: 8,
      aproveitamento: 53,
      variacao_posicao: 0,
      ultimos_jogos: ["e", "d", "v", "d", "v"],
    },
    {
      posicao: 7,
      pontos: 45,
      time: {
        time_id: 44,
        nome_popular: "Internacional",
        sigla: "INT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349b92103.svg",
      },
      jogos: 27,
      vitorias: 12,
      empates: 9,
      derrotas: 6,
      gols_pro: 35,
      gols_contra: 24,
      saldo_gols: 11,
      aproveitamento: 55,
      variacao_posicao: 1,
      ultimos_jogos: ["v", "v", "v", "v", "v"],
    },
    {
      posicao: 8,
      pontos: 43,
      time: {
        time_id: 37,
        nome_popular: "Cruzeiro",
        sigla: "CRU",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34984830b.svg",
      },
      jogos: 28,
      vitorias: 12,
      empates: 7,
      derrotas: 9,
      gols_pro: 35,
      gols_contra: 28,
      saldo_gols: 7,
      aproveitamento: 51,
      variacao_posicao: -1,
      ultimos_jogos: ["d", "v", "d", "e", "e"],
    },
    {
      posicao: 9,
      pontos: 36,
      time: {
        time_id: 23,
        nome_popular: "Vasco",
        sigla: "VAS",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3490f1e73.svg",
      },
      jogos: 27,
      vitorias: 10,
      empates: 6,
      derrotas: 11,
      gols_pro: 31,
      gols_contra: 37,
      saldo_gols: -6,
      aproveitamento: 44,
      variacao_posicao: 1,
      ultimos_jogos: ["v", "v", "e", "d", "e"],
    },
    {
      posicao: 10,
      pontos: 36,
      time: {
        time_id: 30,
        nome_popular: "Atlético-MG",
        sigla: "CAM",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3494f3380.svg",
      },
      jogos: 26,
      vitorias: 9,
      empates: 9,
      derrotas: 8,
      gols_pro: 36,
      gols_contra: 38,
      saldo_gols: -2,
      aproveitamento: 46,
      variacao_posicao: -1,
      ultimos_jogos: ["d", "v", "d", "v", "d"],
    },
    {
      posicao: 11,
      pontos: 33,
      time: {
        time_id: 64,
        nome_popular: "Bragantino",
        sigla: "BGT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a5db2ec.svg",
      },
      jogos: 28,
      vitorias: 8,
      empates: 9,
      derrotas: 11,
      gols_pro: 34,
      gols_contra: 38,
      saldo_gols: -4,
      aproveitamento: 39,
      variacao_posicao: 0,
      ultimos_jogos: ["d", "v", "e", "d", "e"],
    },
    {
      posicao: 12,
      pontos: 33,
      time: {
        time_id: 43,
        nome_popular: "Juventude",
        sigla: "JUV",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349b308c6.svg",
      },
      jogos: 28,
      vitorias: 8,
      empates: 9,
      derrotas: 11,
      gols_pro: 32,
      gols_contra: 38,
      saldo_gols: -6,
      aproveitamento: 39,
      variacao_posicao: 0,
      ultimos_jogos: ["d", "d", "v", "d", "e"],
    },
    {
      posicao: 13,
      pontos: 32,
      time: {
        time_id: 45,
        nome_popular: "Grêmio",
        sigla: "GRE",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349c32bf1.svg",
      },
      jogos: 27,
      vitorias: 9,
      empates: 5,
      derrotas: 13,
      gols_pro: 29,
      gols_contra: 34,
      saldo_gols: -5,
      aproveitamento: 39,
      variacao_posicao: 1,
      ultimos_jogos: ["v", "d", "e", "v", "e"],
    },
    {
      posicao: 14,
      pontos: 32,
      time: {
        time_id: 1,
        nome_popular: "Criciúma",
        sigla: "CRI",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3482a8351.svg",
      },
      jogos: 28,
      vitorias: 8,
      empates: 8,
      derrotas: 12,
      gols_pro: 34,
      gols_contra: 42,
      saldo_gols: -8,
      aproveitamento: 38,
      variacao_posicao: -1,
      ultimos_jogos: ["d", "d", "d", "e", "d"],
    },
    {
      posicao: 15,
      pontos: 31,
      time: {
        time_id: 185,
        nome_popular: "Athletico-PR",
        sigla: "CAP",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34e1b8948.svg",
      },
      jogos: 26,
      vitorias: 8,
      empates: 7,
      derrotas: 11,
      gols_pro: 27,
      gols_contra: 30,
      saldo_gols: -3,
      aproveitamento: 39,
      variacao_posicao: 0,
      ultimos_jogos: ["d", "d", "e", "e", "d"],
    },
    {
      posicao: 16,
      pontos: 28,
      time: {
        time_id: 102,
        nome_popular: "Vitória",
        sigla: "VIT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34bb4bf99.svg",
      },
      jogos: 28,
      vitorias: 8,
      empates: 4,
      derrotas: 16,
      gols_pro: 30,
      gols_contra: 42,
      saldo_gols: -12,
      aproveitamento: 33,
      variacao_posicao: 0,
      ultimos_jogos: ["d", "d", "v", "v", "d"],
    },
    {
      posicao: 17,
      pontos: 28,
      time: {
        time_id: 65,
        nome_popular: "Corinthians",
        sigla: "COR",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a68419f.svg",
      },
      jogos: 28,
      vitorias: 6,
      empates: 10,
      derrotas: 12,
      gols_pro: 27,
      gols_contra: 36,
      saldo_gols: -9,
      aproveitamento: 33,
      variacao_posicao: 0,
      ultimos_jogos: ["d", "v", "d", "v", "d"],
    },
    {
      posicao: 18,
      pontos: 27,
      time: {
        time_id: 26,
        nome_popular: "Fluminense",
        sigla: "FLU",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3492a6e0b.svg",
      },
      jogos: 27,
      vitorias: 7,
      empates: 6,
      derrotas: 14,
      gols_pro: 21,
      gols_contra: 30,
      saldo_gols: -9,
      aproveitamento: 33,
      variacao_posicao: 0,
      ultimos_jogos: ["v", "v", "d", "d", "d"],
    },
    {
      posicao: 19,
      pontos: 23,
      time: {
        time_id: 204,
        nome_popular: "Cuiabá",
        sigla: "CUI",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34ebcdafa.svg",
      },
      jogos: 27,
      vitorias: 5,
      empates: 8,
      derrotas: 14,
      gols_pro: 23,
      gols_contra: 39,
      saldo_gols: -16,
      aproveitamento: 28,
      variacao_posicao: 0,
      ultimos_jogos: ["d", "v", "d", "e", "d"],
    },
    {
      posicao: 20,
      pontos: 21,
      time: {
        time_id: 98,
        nome_popular: "Atlético-GO",
        sigla: "ACG",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34b9174a3.svg",
      },
      jogos: 28,
      vitorias: 5,
      empates: 6,
      derrotas: 17,
      gols_pro: 22,
      gols_contra: 45,
      saldo_gols: -23,
      aproveitamento: 25,
      variacao_posicao: 0,
      ultimos_jogos: ["v", "d", "d", "d", "v"],
    },
  ];

app.get('/', (req, res) => {
    res.send(tabela_brasileirao);
});

app.listen(port, '0.0.0.0', () => {  // Escute em 0.0.0.0
    console.log(`Server is running on http://0.0.0.0:${port}`);
});
